"""
Artifact Manager — storage and retrieval of agent-generated files.

Artifacts are files generated by agents (PDFs, PPTX, CSV, DOCX) or uploaded
directly by users. They are stored at a configurable path on the server
filesystem (EBS in prod) and tracked in the `artifacts` table.

DB table `artifacts`:
  id, user_id, session_id, filename, file_path, file_type,
  scope, department, folder_id, created_at

Scopes:
  personal   — owner-only; stored at {base}/{dept}/{email}/
  department — all dept members; stored at {base}/{dept}/shared/
  company    — all users; stored at {base}/company/

Download URL pattern: /files/{artifact_id}
"""

import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import httpx
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger("mezzofy.context.artifacts")

_DEFAULT_ARTIFACTS_DIR = Path("/var/mezzofy/artifacts")


def get_artifacts_dir() -> Path:
    """Return the root directory where generated files are stored."""
    env_path = os.getenv("ARTIFACTS_DIR")
    if env_path:
        return Path(env_path)
    return _DEFAULT_ARTIFACTS_DIR


def get_user_artifacts_dir(dept: str, email: str) -> Path:
    """
    Return the per-user directory: {base}/{dept}/{email}/
    Creates it if it doesn't exist.
    """
    for val, label in [(dept, "department"), (email, "email")]:
        if not val or '/' in val or '\\' in val or '..' in val or '\x00' in val:
            raise ValueError(f"Invalid {label} in artifact path: {val!r}")
    path = get_artifacts_dir() / dept / email
    path.mkdir(parents=True, exist_ok=True)
    return path


def get_dept_artifacts_dir(dept: str) -> Path:
    """
    Return the department shared directory: {base}/{dept}/shared/
    Creates it if it doesn't exist.
    """
    path = get_artifacts_dir() / dept / "shared"
    path.mkdir(parents=True, exist_ok=True)
    return path


def get_company_artifacts_dir() -> Path:
    """
    Return the company-wide public directory: {base}/company/
    Creates it if it doesn't exist.
    """
    path = get_artifacts_dir() / "company"
    path.mkdir(parents=True, exist_ok=True)
    return path


async def register_artifact(
    db: AsyncSession,
    user_id: str,
    session_id: Optional[str],
    filename: str,
    file_path: str,
    file_type: str,
    scope: str = "personal",
    folder_id: Optional[str] = None,
    department: Optional[str] = None,
) -> dict:
    """
    Register a generated or uploaded file in the artifacts table.

    The file must already exist at file_path on the filesystem.

    Args:
        db:         Active DB session.
        user_id:    Owner of the artifact.
        session_id: Conversation session that produced this artifact (None for uploads).
        filename:   Display filename (e.g. "sales_report_Q1.pdf").
        file_path:  Absolute path to the file on disk.
        file_type:  MIME-style type string ("pdf", "pptx", "docx", "csv").
        scope:      Access scope: "personal" | "department" | "company".
        folder_id:  Optional folder UUID to place the file in.
        department: Department name (for dept/company scoped files).

    Returns:
        {id, filename, file_type, download_url}
    """
    artifact_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)

    try:
        await db.execute(
            text(
                """
                INSERT INTO artifacts
                  (id, user_id, session_id, filename, file_path, file_type,
                   scope, department, folder_id, created_at)
                VALUES
                  (:id, :uid, :sid, :fname, :fpath, :ftype,
                   :scope, :dept, :folder_id, :now)
                """
            ),
            {
                "id": artifact_id,
                "uid": user_id,
                "sid": str(session_id) if session_id is not None else None,
                "fname": filename,
                "fpath": file_path,
                "ftype": file_type,
                "scope": scope,
                "dept": department,
                "folder_id": folder_id,
                "now": now,
            },
        )
        logger.debug(f"Registered artifact {artifact_id}: {filename} (scope={scope})")
    except Exception as e:
        logger.error(f"Failed to register artifact {filename}: {e}")

    return {
        "id": artifact_id,
        "filename": filename,
        "file_type": file_type,
        "download_url": f"/files/{artifact_id}",
    }


async def get_artifact(
    db: AsyncSession,
    artifact_id: str,
) -> Optional[dict]:
    """
    Retrieve artifact metadata by ID.

    Does NOT enforce access control — the caller (files.py) must perform
    the RBAC check based on the returned scope/user_id/department fields.

    Returns None if the artifact does not exist.
    """
    result = await db.execute(
        text(
            """
            SELECT id, user_id, filename, file_path, file_type,
                   scope, department, folder_id, created_at
            FROM artifacts
            WHERE id = :id
            """
        ),
        {"id": artifact_id},
    )
    row = result.fetchone()
    if row is None:
        return None
    return {
        "id": str(row.id),
        "user_id": str(row.user_id),
        "filename": row.filename,
        "file_path": row.file_path,
        "file_type": row.file_type,
        "scope": row.scope or "personal",
        "department": row.department,
        "folder_id": str(row.folder_id) if row.folder_id else None,
        "download_url": f"/files/{row.id}",
        "created_at": row.created_at.isoformat() if row.created_at else None,
    }


async def list_artifacts(
    db: AsyncSession,
    scope: str,
    user_id: str,
    department: str,
    folder_id: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
) -> list:
    """
    List artifacts accessible to the user for the given scope.

    - personal:   user_id matches
    - department: department matches
    - company:    all (no ownership filter)

    folder_id=None → root-level files only (folder_id IS NULL)
    folder_id=str  → files inside that specific folder
    """
    base_filter = ""
    params: dict = {"lim": limit, "off": offset}

    if scope == "personal":
        base_filter = "a.scope = 'personal' AND a.user_id = :uid"
        params["uid"] = user_id
    elif scope == "department":
        base_filter = "a.scope = 'department' AND a.department = :dept"
        params["dept"] = department
    else:  # company
        base_filter = "a.scope = 'company'"

    if folder_id is not None:
        try:
            params["fid"] = uuid.UUID(str(folder_id))
        except (ValueError, AttributeError):
            return []          # invalid UUID string → empty list, no DB error
        folder_filter = "AND a.folder_id = :fid"
    else:
        folder_filter = "AND a.folder_id IS NULL"

    result = await db.execute(
        text(
            f"""
            SELECT a.id, a.filename, a.file_type, a.scope,
                   a.folder_id, a.created_at,
                   a.user_id AS created_by_id, u.name AS creator_name
            FROM artifacts a
            LEFT JOIN users u ON u.id = a.user_id
            WHERE {base_filter} {folder_filter}
            ORDER BY a.created_at DESC
            LIMIT :lim OFFSET :off
            """
        ),
        params,
    )
    return [
        {
            "id": str(row.id),
            "filename": row.filename,
            "file_type": row.file_type,
            "scope": row.scope or "personal",
            "folder_id": str(row.folder_id) if row.folder_id else None,
            "download_url": f"/files/{row.id}",
            "created_at": row.created_at.isoformat() if row.created_at else None,
            "creator_name": row.creator_name or "Unknown",
            "created_by_id": str(row.created_by_id),
        }
        for row in result.fetchall()
    ]


async def list_user_artifacts(
    db: AsyncSession,
    user_id: str,
    limit: int = 50,
    offset: int = 0,
) -> list:
    """
    Backward-compatible wrapper: list personal artifacts for a user.
    New code should use list_artifacts() with scope parameter.
    """
    return await list_artifacts(
        db=db,
        scope="personal",
        user_id=user_id,
        department="",
        folder_id=None,
        limit=limit,
        offset=offset,
    )


async def sync_user_artifacts(
    db: AsyncSession,
    user_id: str,
    department: str,
    email: str,
) -> int:
    """
    Scan the user's personal artifact directory on disk and register any files
    not already in the artifacts table (scope='personal').

    Returns the count of newly registered files.
    Skips: .md files (system files used by the AI agent).
    Called transparently on every GET /files/?scope=personal request.
    """
    user_dir = get_user_artifacts_dir(department, email)
    if not user_dir.exists():
        return 0

    result = await db.execute(
        text("SELECT filename FROM artifacts WHERE user_id = :uid AND scope = 'personal'"),
        {"uid": user_id},
    )
    registered = {row[0] for row in result.fetchall()}

    SKIP_EXTENSIONS = {".md"}
    ALLOWED_EXTENSIONS = {".txt", ".pdf", ".docx", ".pptx", ".xlsx", ".csv", ".mp3", ".mp4"}

    newly_registered = 0
    for file_path in user_dir.iterdir():
        if not file_path.is_file():
            continue
        suffix = file_path.suffix.lower()
        if suffix in SKIP_EXTENSIONS:
            continue
        if suffix not in ALLOWED_EXTENSIONS:
            continue
        if file_path.name in registered:
            continue
        file_type = suffix.lstrip(".")
        await register_artifact(
            db=db,
            user_id=user_id,
            session_id=None,
            filename=file_path.name,
            file_path=str(file_path),
            file_type=file_type,
            scope="personal",
            department=department,
        )
        newly_registered += 1

    if newly_registered:
        await db.commit()
        logger.info(
            f"sync_user_artifacts: registered {newly_registered} orphaned file(s) "
            f"for user_id={user_id}"
        )
    return newly_registered


async def sync_dept_artifacts(
    db: AsyncSession,
    user_id: str,
    dept: str,
) -> int:
    """
    Scan the department shared directory on disk and register any files
    not already in the artifacts table (scope='department').

    Returns the count of newly registered files.
    Skips: .md files (system files used by the AI agent).
    Called transparently on every GET /files/?scope=department request.
    """
    dept_dir = get_dept_artifacts_dir(dept)
    if not dept_dir.exists():
        return 0

    result = await db.execute(
        text(
            "SELECT filename FROM artifacts "
            "WHERE scope = 'department' AND department = :dept"
        ),
        {"dept": dept},
    )
    registered = {row[0] for row in result.fetchall()}

    SKIP_EXTENSIONS = {".md"}
    ALLOWED_EXTENSIONS = {".txt", ".pdf", ".docx", ".pptx", ".xlsx", ".csv", ".mp3", ".mp4"}

    newly_registered = 0
    for file_path in dept_dir.iterdir():
        if not file_path.is_file():
            continue
        suffix = file_path.suffix.lower()
        if suffix in SKIP_EXTENSIONS:
            continue
        if suffix not in ALLOWED_EXTENSIONS:
            continue
        if file_path.name in registered:
            continue
        file_type = suffix.lstrip(".")
        await register_artifact(
            db=db,
            user_id=user_id,
            session_id=None,
            filename=file_path.name,
            file_path=str(file_path),
            file_type=file_type,
            scope="department",
            department=dept,
        )
        newly_registered += 1

    if newly_registered:
        await db.commit()
        logger.info(
            f"sync_dept_artifacts: registered {newly_registered} orphaned file(s) "
            f"for dept={dept}"
        )
    return newly_registered


# ── Anthropic Files API integration ───────────────────────────────────────────

_FILES_API_BASE = "https://api.anthropic.com/v1/files"
_FILES_API_BETA = "files-api-2025-04-14"

_SKILL_EXTENSIONS = {
    "pptx": (".pptx", "pptx", "presentations"),
    "xlsx": (".xlsx", "xlsx", "exports"),
    "pdf":  (".pdf",  "pdf",  "documents"),
    "docx": (".docx", "docx", "documents"),
}


def _get_anthropic_api_key() -> str:
    """Retrieve the Anthropic API key from environment."""
    return os.getenv("ANTHROPIC_API_KEY", "")


def _anthropic_headers() -> dict:
    """Return standard Anthropic API headers for Files API calls."""
    return {
        "x-api-key":         _get_anthropic_api_key(),
        "anthropic-version": "2023-06-01",
        "anthropic-beta":    _FILES_API_BETA,
    }


async def download_from_anthropic(
    db: AsyncSession,
    file_id: str,
    user_id: str,
    session_id: str,
    skill_id: str,
    suggested_name: str = None,
    agent_id: str = None,
    department: str = None,
) -> dict:
    """
    Download a file from Anthropic Files API and store it in our artifact system.

    This is called immediately after generate_document_with_skill() returns file_ids.
    It bridges the Anthropic Files API → our local artifact storage → artifacts DB table.

    Args:
        db:             Active DB session.
        file_id:        Anthropic Files API ID (from Skills response)
        user_id:        Owner user_id (for RBAC)
        session_id:     Associated conversation session
        skill_id:       "pptx" | "xlsx" | "pdf" | "docx" (for file extension + type)
        suggested_name: Base filename without extension (auto-generated if None)
        agent_id:       Which agent generated this file (for audit)
        department:     Department for scope/path resolution

    Returns:
        {
          artifact_id:  str,   # Our local artifacts table UUID
          file_path:    str,   # Local EBS/S3 path
          download_url: str,   # Our API download URL
          size_bytes:   int,
        }
    """
    ext, file_type, subdir = _SKILL_EXTENSIONS.get(skill_id, (".bin", "file", "uploads"))

    # Auto-generate filename if not provided
    if not suggested_name:
        import time
        suggested_name = f"{skill_id}_{int(time.time())}"
    filename = suggested_name + ext

    # Download from Anthropic Files API
    async with httpx.AsyncClient(timeout=120.0) as client:
        response = await client.get(
            f"{_FILES_API_BASE}/{file_id}/content",
            headers=_anthropic_headers(),
        )
        response.raise_for_status()
        file_bytes = response.content

    # Save to local artifact storage
    base_dir = get_artifacts_dir()
    dest_dir  = base_dir / subdir
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest_path = dest_dir / filename
    dest_path.write_bytes(file_bytes)

    # Record in artifacts table (with anthropic_file_id, skill_id, generation_source)
    artifact_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)

    try:
        await db.execute(
            text("""
                INSERT INTO artifacts
                  (id, user_id, session_id, filename, file_path, file_type,
                   scope, department, created_at,
                   anthropic_file_id, skill_id, generation_source)
                VALUES
                  (:id, :uid, :sid, :fname, :fpath, :ftype,
                   :scope, :dept, :now,
                   :anthropic_file_id, :skill_id, :generation_source)
            """),
            {
                "id":               artifact_id,
                "uid":              user_id,
                "sid":              str(session_id) if session_id else None,
                "fname":            filename,
                "fpath":            str(dest_path),
                "ftype":            file_type,
                "scope":            "personal",
                "dept":             department,
                "now":              now,
                "anthropic_file_id": file_id,
                "skill_id":         skill_id,
                "generation_source": "anthropic_skill",
            },
        )
        await db.commit()
    except Exception as e:
        logger.warning(
            f"download_from_anthropic: DB insert failed (new columns may not be migrated yet) — {e}"
        )
        # Fallback: insert without the new columns
        try:
            await db.rollback()
            await db.execute(
                text("""
                    INSERT INTO artifacts
                      (id, user_id, session_id, filename, file_path, file_type,
                       scope, department, created_at, anthropic_file_id)
                    VALUES
                      (:id, :uid, :sid, :fname, :fpath, :ftype,
                       :scope, :dept, :now, :anthropic_file_id)
                """),
                {
                    "id":               artifact_id,
                    "uid":              user_id,
                    "sid":              str(session_id) if session_id else None,
                    "fname":            filename,
                    "fpath":            str(dest_path),
                    "ftype":            file_type,
                    "scope":            "personal",
                    "dept":             department,
                    "now":              now,
                    "anthropic_file_id": file_id,
                },
            )
            await db.commit()
        except Exception as e2:
            logger.error(f"download_from_anthropic: fallback DB insert also failed: {e2}")

    # Delete from Anthropic Files API after downloading (saves Anthropic storage cost)
    await _delete_anthropic_file(file_id)

    logger.info(
        f"download_from_anthropic: saved {filename} ({len(file_bytes)} bytes) "
        f"artifact_id={artifact_id}"
    )
    return {
        "artifact_id":  artifact_id,
        "file_path":    str(dest_path),
        "download_url": f"/files/{artifact_id}",
        "size_bytes":   len(file_bytes),
    }


async def _delete_anthropic_file(file_id: str) -> None:
    """Delete file from Anthropic Files API after we've downloaded it (non-fatal)."""
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            await client.delete(
                f"{_FILES_API_BASE}/{file_id}",
                headers=_anthropic_headers(),
            )
    except Exception as e:
        logger.warning(f"_delete_anthropic_file: failed to delete {file_id}: {e}")


async def upload_to_anthropic(file_path: str, media_type: str = None) -> str:
    """
    Upload a local file to Anthropic Files API for use in API calls.
    Returns the Anthropic file_id.

    Use case: uploading user-provided PDFs/DOCX for Claude to read and analyse,
    without re-uploading on every API call (Files API caches them).
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    # Auto-detect media type if not provided
    if media_type is None:
        _MEDIA_TYPES = {
            ".pdf":  "application/pdf",
            ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ".png":  "image/png",
            ".jpg":  "image/jpeg",
            ".jpeg": "image/jpeg",
            ".txt":  "text/plain",
            ".csv":  "text/csv",
        }
        media_type = _MEDIA_TYPES.get(path.suffix.lower(), "application/octet-stream")

    async with httpx.AsyncClient(timeout=120.0) as client:
        with open(path, "rb") as f:
            response = await client.post(
                _FILES_API_BASE,
                headers=_anthropic_headers(),
                files={"file": (path.name, f, media_type)},
            )
        response.raise_for_status()
        return response.json()["id"]


async def list_anthropic_files(user_id: str = None) -> list:
    """
    List files currently stored in Anthropic Files API.
    Returns list of {id, filename, created_at, size} dicts.
    (user_id is for logging/audit only — Anthropic Files API is global per API key.)
    """
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.get(
                _FILES_API_BASE,
                headers=_anthropic_headers(),
            )
            response.raise_for_status()
            data = response.json()
            return data.get("data", [])
    except Exception as e:
        logger.warning(f"list_anthropic_files: failed: {e}")
        return []


async def delete_from_anthropic(file_id: str) -> bool:
    """
    Explicitly delete a file from Anthropic Files API.
    Returns True if deleted, False if error.
    """
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.delete(
                f"{_FILES_API_BASE}/{file_id}",
                headers=_anthropic_headers(),
            )
            response.raise_for_status()
            return True
    except Exception as e:
        logger.warning(f"delete_from_anthropic: failed for {file_id}: {e}")
        return False
