"""
Artifact Manager — storage and retrieval of agent-generated files.

Artifacts are files generated by agents (PDFs, PPTX, CSV, DOCX) or uploaded
directly by users. They are stored at a configurable path on the server
filesystem (EBS in prod) and tracked in the `artifacts` table.

DB table `artifacts`:
  id, user_id, session_id, filename, file_path, file_type,
  scope, department, folder_id, created_at

Scopes:
  personal   — owner-only; stored at {base}/{dept}/{email}/
  department — all dept members; stored at {base}/{dept}/shared/
  company    — all users; stored at {base}/company/

Download URL pattern: /files/{artifact_id}
"""

import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger("mezzofy.context.artifacts")

_DEFAULT_ARTIFACTS_DIR = Path("/var/mezzofy/artifacts")


def get_artifacts_dir() -> Path:
    """Return the root directory where generated files are stored."""
    env_path = os.getenv("ARTIFACTS_DIR")
    if env_path:
        return Path(env_path)
    return _DEFAULT_ARTIFACTS_DIR


def get_user_artifacts_dir(dept: str, email: str) -> Path:
    """
    Return the per-user directory: {base}/{dept}/{email}/
    Creates it if it doesn't exist.
    """
    path = get_artifacts_dir() / dept / email
    path.mkdir(parents=True, exist_ok=True)
    return path


def get_dept_artifacts_dir(dept: str) -> Path:
    """
    Return the department shared directory: {base}/{dept}/shared/
    Creates it if it doesn't exist.
    """
    path = get_artifacts_dir() / dept / "shared"
    path.mkdir(parents=True, exist_ok=True)
    return path


def get_company_artifacts_dir() -> Path:
    """
    Return the company-wide public directory: {base}/company/
    Creates it if it doesn't exist.
    """
    path = get_artifacts_dir() / "company"
    path.mkdir(parents=True, exist_ok=True)
    return path


async def register_artifact(
    db: AsyncSession,
    user_id: str,
    session_id: Optional[str],
    filename: str,
    file_path: str,
    file_type: str,
    scope: str = "personal",
    folder_id: Optional[str] = None,
    department: Optional[str] = None,
) -> dict:
    """
    Register a generated or uploaded file in the artifacts table.

    The file must already exist at file_path on the filesystem.

    Args:
        db:         Active DB session.
        user_id:    Owner of the artifact.
        session_id: Conversation session that produced this artifact (None for uploads).
        filename:   Display filename (e.g. "sales_report_Q1.pdf").
        file_path:  Absolute path to the file on disk.
        file_type:  MIME-style type string ("pdf", "pptx", "docx", "csv").
        scope:      Access scope: "personal" | "department" | "company".
        folder_id:  Optional folder UUID to place the file in.
        department: Department name (for dept/company scoped files).

    Returns:
        {id, filename, file_type, download_url}
    """
    artifact_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)

    try:
        await db.execute(
            text(
                """
                INSERT INTO artifacts
                  (id, user_id, session_id, filename, file_path, file_type,
                   scope, department, folder_id, created_at)
                VALUES
                  (:id, :uid, :sid, :fname, :fpath, :ftype,
                   :scope, :dept, :folder_id, :now)
                """
            ),
            {
                "id": artifact_id,
                "uid": user_id,
                "sid": session_id,
                "fname": filename,
                "fpath": file_path,
                "ftype": file_type,
                "scope": scope,
                "dept": department,
                "folder_id": folder_id,
                "now": now,
            },
        )
        logger.debug(f"Registered artifact {artifact_id}: {filename} (scope={scope})")
    except Exception as e:
        logger.error(f"Failed to register artifact {filename}: {e}")

    return {
        "id": artifact_id,
        "filename": filename,
        "file_type": file_type,
        "download_url": f"/files/{artifact_id}",
    }


async def get_artifact(
    db: AsyncSession,
    artifact_id: str,
) -> Optional[dict]:
    """
    Retrieve artifact metadata by ID.

    Does NOT enforce access control — the caller (files.py) must perform
    the RBAC check based on the returned scope/user_id/department fields.

    Returns None if the artifact does not exist.
    """
    result = await db.execute(
        text(
            """
            SELECT id, user_id, filename, file_path, file_type,
                   scope, department, folder_id, created_at
            FROM artifacts
            WHERE id = :id
            """
        ),
        {"id": artifact_id},
    )
    row = result.fetchone()
    if row is None:
        return None
    return {
        "id": str(row.id),
        "user_id": str(row.user_id),
        "filename": row.filename,
        "file_path": row.file_path,
        "file_type": row.file_type,
        "scope": row.scope or "personal",
        "department": row.department,
        "folder_id": str(row.folder_id) if row.folder_id else None,
        "download_url": f"/files/{row.id}",
        "created_at": row.created_at.isoformat() if row.created_at else None,
    }


async def list_artifacts(
    db: AsyncSession,
    scope: str,
    user_id: str,
    department: str,
    folder_id: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
) -> list:
    """
    List artifacts accessible to the user for the given scope.

    - personal:   user_id matches
    - department: department matches
    - company:    all (no ownership filter)

    folder_id=None → root-level files only (folder_id IS NULL)
    folder_id=str  → files inside that specific folder
    """
    base_filter = ""
    params: dict = {"lim": limit, "off": offset}

    if scope == "personal":
        base_filter = "a.scope = 'personal' AND a.user_id = :uid"
        params["uid"] = user_id
    elif scope == "department":
        base_filter = "a.scope = 'department' AND a.department = :dept"
        params["dept"] = department
    else:  # company
        base_filter = "a.scope = 'company'"

    if folder_id is not None:
        folder_filter = "AND a.folder_id = :fid"
        params["fid"] = folder_id
    else:
        folder_filter = "AND a.folder_id IS NULL"

    result = await db.execute(
        text(
            f"""
            SELECT a.id, a.filename, a.file_type, a.scope,
                   a.folder_id, a.created_at
            FROM artifacts a
            WHERE {base_filter} {folder_filter}
            ORDER BY a.created_at DESC
            LIMIT :lim OFFSET :off
            """
        ),
        params,
    )
    return [
        {
            "id": str(row.id),
            "filename": row.filename,
            "file_type": row.file_type,
            "scope": row.scope or "personal",
            "folder_id": str(row.folder_id) if row.folder_id else None,
            "download_url": f"/files/{row.id}",
            "created_at": row.created_at.isoformat() if row.created_at else None,
        }
        for row in result.fetchall()
    ]


async def list_user_artifacts(
    db: AsyncSession,
    user_id: str,
    limit: int = 50,
    offset: int = 0,
) -> list:
    """
    Backward-compatible wrapper: list personal artifacts for a user.
    New code should use list_artifacts() with scope parameter.
    """
    return await list_artifacts(
        db=db,
        scope="personal",
        user_id=user_id,
        department="",
        folder_id=None,
        limit=limit,
        offset=offset,
    )


async def sync_user_artifacts(
    db: AsyncSession,
    user_id: str,
    department: str,
    email: str,
) -> int:
    """
    Scan the user's personal artifact directory on disk and register any files
    not already in the artifacts table (scope='personal').

    Returns the count of newly registered files.
    Skips: .md files (system files used by the AI agent).
    Called transparently on every GET /files/?scope=personal request.
    """
    user_dir = get_user_artifacts_dir(department, email)
    if not user_dir.exists():
        return 0

    result = await db.execute(
        text("SELECT filename FROM artifacts WHERE user_id = :uid AND scope = 'personal'"),
        {"uid": user_id},
    )
    registered = {row[0] for row in result.fetchall()}

    SKIP_EXTENSIONS = {".md"}
    ALLOWED_EXTENSIONS = {".txt", ".pdf", ".docx", ".pptx", ".xlsx", ".csv", ".mp3", ".mp4"}

    newly_registered = 0
    for file_path in user_dir.iterdir():
        if not file_path.is_file():
            continue
        suffix = file_path.suffix.lower()
        if suffix in SKIP_EXTENSIONS:
            continue
        if suffix not in ALLOWED_EXTENSIONS:
            continue
        if file_path.name in registered:
            continue
        file_type = suffix.lstrip(".")
        await register_artifact(
            db=db,
            user_id=user_id,
            session_id=None,
            filename=file_path.name,
            file_path=str(file_path),
            file_type=file_type,
            scope="personal",
            department=department,
        )
        newly_registered += 1

    if newly_registered:
        await db.commit()
        logger.info(
            f"sync_user_artifacts: registered {newly_registered} orphaned file(s) "
            f"for user_id={user_id}"
        )
    return newly_registered
