"""
LegalAgent — Leo, the Legal Specialist.

Leo reviews and drafts business contracts, provides jurisdiction-specific legal
advisory, and assesses legal risk across 7 supported jurisdictions:
    Singapore, Hong Kong, Malaysia, UAE, Saudi Arabia, Qatar, Cayman Islands.

Routing:
    Dispatched when chat.py detects legal keywords and sets task["agent"] = "legal",
    or when task["agent_override"] == "legal" (Management Agent delegation).

    can_handle: task["agent_override"] == "legal" OR legal keyword in message
    execute:    classify → route to workflow → append disclaimer → log

LEGAL DISCLAIMER:
    All Leo outputs include a mandatory disclaimer that this is AI-generated
    analysis for reference only and does not constitute professional legal advice.
"""

import logging
from pathlib import Path

from app.agents.base_agent import BaseAgent

logger = logging.getLogger("mezzofy.agents.legal")

# ── Constants ─────────────────────────────────────────────────────────────────

LEGAL_DISCLAIMER = (
    "\n\n---\n"
    "**Legal Disclaimer:** This analysis is generated by Leo, an AI legal assistant, "
    "for reference and informational purposes only. It does not constitute professional "
    "legal advice and should not be relied upon as such. Laws and regulations vary by "
    "jurisdiction and may change. Please consult a qualified solicitor or legal "
    "professional before making any decisions based on this information."
)

LEGAL_TRIGGERS = [
    # Document types
    "contract", "nda", "non-disclosure", "agreement", "mou", "memorandum of understanding",
    "term sheet", "letter of intent", "loi", "shareholder agreement", "shareholders agreement",
    "employment contract", "vendor agreement", "service agreement", "consultancy agreement",
    "ip assignment", "distribution agreement", "licensing agreement",
    # Actions
    "legal advice", "legal advisory", "legal review", "review contract", "review agreement",
    "review document", "draft contract", "draft agreement", "draft nda",
    "legal analysis", "legal risk", "legal opinion", "legal document",
    "contract review", "contract draft", "contract clause",
    # Legal concepts
    "clause", "indemnity", "liability", "force majeure", "governing law",
    "jurisdiction", "dispute resolution", "arbitration", "confidentiality",
    "intellectual property", "ip rights", "termination clause",
    "compliance", "regulatory", "gdpr", "data protection",
    # Jurisdictions (as standalone legal triggers)
    "singapore law", "hong kong law", "malaysia law", "uae law",
    "cayman islands", "cayman law",
]

# ── Jurisdiction → knowledge file mapping ─────────────────────────────────────

_JURISDICTION_MAP = {
    "singapore": "singapore",
    "sg": "singapore",
    "hong kong": "hong_kong",
    "hk": "hong_kong",
    "malaysia": "malaysia",
    "my": "malaysia",
    "uae": "uae",
    "united arab emirates": "uae",
    "saudi arabia": "saudi_arabia",
    "ksa": "saudi_arabia",
    "qatar": "qatar",
    "qa": "qatar",
    "cayman islands": "cayman_islands",
    "cayman": "cayman_islands",
}

_KNOWLEDGE_BASE_PATH = Path(__file__).parent.parent.parent / "knowledge" / "legal"


class LegalAgent(BaseAgent):
    """
    Leo — Legal Specialist Agent.

    Handles legal document review, contract drafting, clause extraction,
    risk assessment, and jurisdiction-specific advisory.

    can_handle: agent_override == "legal" OR legal trigger keyword in message
    execute:    classify → route workflow → append LEGAL_DISCLAIMER → log
    """

    def can_handle(self, task: dict) -> bool:
        """
        Return True if:
          (a) task was explicitly routed to legal (agent_override == "legal"), OR
          (b) the message contains a legal trigger keyword.
        """
        if task.get("agent_override") == "legal":
            return True
        if task.get("agent") == "legal":
            return True
        message = task.get("message", "").lower()
        return any(trigger in message for trigger in LEGAL_TRIGGERS)

    async def execute(self, task: dict) -> dict:
        """
        Main dispatch entry point for all legal workflows.

        Flow:
          1. log_task_start
          2. _classify_legal_task → workflow name
          3. Route to correct async workflow method
          4. Append LEGAL_DISCLAIMER to content
          5. log_task_complete / log_task_failed
          6. Return result
        """
        await self.load_agent_record("agent_legal")
        task_log_id = await self.log_task_start(task)

        message = task.get("message", "")
        logger.info(
            f"LegalAgent.execute: user_id={task.get('user_id')} "
            f"message={message[:80]!r}"
        )

        try:
            workflow = self._classify_legal_task(message)
            logger.info(f"LegalAgent: classified workflow={workflow!r}")

            if workflow == "review_document":
                result = await self.review_document(task)
            elif workflow == "generate_contract":
                result = await self.generate_contract(task)
            elif workflow == "extract_clauses":
                result = await self.extract_clauses(task)
            elif workflow == "assess_legal_risk":
                result = await self.assess_legal_risk(task)
            else:
                # Default: provide_legal_advice covers general legal questions
                result = await self.provide_legal_advice(task)

            # Append disclaimer to ALL content — non-negotiable
            if result.get("success") and result.get("content"):
                result["content"] = result["content"] + LEGAL_DISCLAIMER

            await self.log_task_complete(task_log_id, result)
            result.setdefault("agent_used", "legal")
            return result

        except Exception as exc:
            logger.error(f"LegalAgent.execute failed: {exc}", exc_info=True)
            await self.log_task_failed(task_log_id, str(exc))
            err = self._err(f"Leo encountered an error: {exc}{LEGAL_DISCLAIMER}")
            err["agent_used"] = "legal"
            return err

    # ── Workflow methods ───────────────────────────────────────────────────────

    async def review_document(self, task: dict) -> dict:
        """
        Review an uploaded legal document (PDF or DOCX).

        Extracts text, identifies document type, parties, governing law,
        key dates, and potential risk areas. Produces a structured review report.
        """
        config = task.get("_config", {})
        message = task.get("message", "")
        jurisdiction = self._classify_jurisdiction(message)

        logger.info(f"LegalAgent.review_document: jurisdiction={jurisdiction!r}")

        # Load jurisdiction knowledge if available
        kb_context = self._load_jurisdiction_knowledge(jurisdiction)

        # Build system prompt for document review
        system_prompt = (
            "You are Leo, a specialist legal AI assistant for Mezzofy. "
            "You are reviewing a legal document on behalf of the user. "
            "Your analysis must be structured, precise, and jurisdiction-aware.\n\n"
            "When reviewing a document, always cover:\n"
            "1. **Document Type** — What type of legal document is this?\n"
            "2. **Parties** — Who are the contracting parties?\n"
            "3. **Governing Law & Jurisdiction** — Which law governs? Which courts?\n"
            "4. **Key Dates** — Effective date, expiry, notice periods.\n"
            "5. **Key Obligations** — What must each party do?\n"
            "6. **Risk Areas** — Unusual clauses, one-sided terms, missing protections.\n"
            "7. **Recommendations** — What should be negotiated or clarified?\n\n"
            + (f"Jurisdiction Context:\n{kb_context}\n\n" if kb_context else "")
            + "Be clear, structured, and practical. Flag red flags prominently."
        )

        try:
            from app.llm import llm_manager as llm_mod

            # Check if there is extracted document text (from send-artifact / send-media flow)
            extracted_text = task.get("extracted_text") or task.get("media_content", {})
            if isinstance(extracted_text, str) and extracted_text:
                # Prepend document text to the message context
                task_with_doc = dict(task)
                task_with_doc["message"] = (
                    f"Please review the following legal document:\n\n"
                    f"{extracted_text[:8000]}\n\n"
                    f"User request: {message}"
                )
                task_with_doc["system_prompt"] = system_prompt
                result = await llm_mod.get().execute_with_tools(task_with_doc)
            else:
                task_with_prompt = dict(task)
                task_with_prompt["system_prompt"] = system_prompt
                result = await llm_mod.get().execute_with_tools(task_with_prompt)

            return self._ok(
                content=result.get("content", "Document review complete."),
                artifacts=result.get("artifacts", []),
                tools_called=result.get("tools_called", ["review_document"]),
            )
        except Exception as exc:
            logger.error(f"LegalAgent.review_document failed: {exc}", exc_info=True)
            return self._err(f"Document review failed: {exc}")

    async def generate_contract(self, task: dict) -> dict:
        """
        Generate a business contract or legal agreement from templates.

        Supports: NDA, Service Agreement, Employment Contract, MOU, Vendor Agreement,
        Consultancy Agreement, IP Assignment, LOI, Distribution Agreement, Shareholders Agreement.
        Uses jurisdiction-specific templates from the knowledge base.
        """
        config = task.get("_config", {})
        message = task.get("message", "")
        jurisdiction = self._classify_jurisdiction(message)

        logger.info(f"LegalAgent.generate_contract: jurisdiction={jurisdiction!r}")

        # Load template and jurisdiction context
        kb_context = self._load_jurisdiction_knowledge(jurisdiction)
        template_context = self._load_contract_template(message, jurisdiction)

        system_prompt = (
            "You are Leo, a specialist legal AI assistant for Mezzofy. "
            "You are drafting a legal agreement on behalf of the user. "
            "Your output must be a complete, professional, jurisdiction-appropriate document.\n\n"
            "Contract drafting guidelines:\n"
            "1. Use clear, unambiguous legal language appropriate for the jurisdiction.\n"
            "2. Include all standard clauses: definitions, obligations, payment, IP, "
            "confidentiality, termination, limitation of liability, dispute resolution, governing law.\n"
            "3. Flag any clauses where user input is needed (e.g., [PARTY A NAME], [EFFECTIVE DATE]).\n"
            "4. Tailor to the jurisdiction — include jurisdiction-specific statutory requirements.\n"
            "5. Structure: Title, Parties, Recitals, Definitions, Body Clauses, Signatures.\n\n"
            + (f"Jurisdiction Context:\n{kb_context}\n\n" if kb_context else "")
            + (f"Template Reference:\n{template_context}\n\n" if template_context else "")
            + "Draft a complete, well-structured document. Use [PLACEHOLDER] for user-specific details."
        )

        try:
            from app.llm import llm_manager as llm_mod

            task_with_prompt = dict(task)
            task_with_prompt["system_prompt"] = system_prompt

            # First: generate contract text via LLM
            text_result = await llm_mod.get().chat(
                messages=[{"role": "user", "content": message}],
                task_context=task_with_prompt,
            )
            contract_text = text_result.get("content", "")

            artifacts = []
            tools_called = ["generate_contract"]

            # Try skill DOCX generation first, fall back to execute_with_tools
            if contract_text:
                docx_title = f"Contract — {message[:60]}"
                try:
                    from app.llm import llm_manager as _llm_mod
                    skill_result = await _llm_mod.get().generate_document_with_skill(
                        skill_id="docx",
                        prompt=contract_text,
                        context_data=None,
                        task_context=task,
                    )
                    if skill_result.get("success") and skill_result.get("file_ids"):
                        from app.context.artifact_manager import download_from_anthropic
                        artifact = await download_from_anthropic(
                            db=task["db"],
                            file_id=skill_result["file_ids"][0],
                            user_id=task["user_id"],
                            session_id=task["session_id"],
                            skill_id="docx",
                            suggested_name=docx_title,
                        )
                        artifacts.append(artifact)
                        tools_called.append("create_docx")
                except Exception as e:
                    logger.warning(f"Skill DOCX generation failed, falling back to execute_with_tools: {e}")
                    fallback = await llm_mod.get().execute_with_tools(task_with_prompt)
                    contract_text = fallback.get("content", contract_text)
                    artifacts = fallback.get("artifacts", [])
                    tools_called = fallback.get("tools_called", tools_called)
            else:
                # No text from chat — fall back to full execute_with_tools
                fallback = await llm_mod.get().execute_with_tools(task_with_prompt)
                contract_text = fallback.get("content", "Contract generation complete.")
                artifacts = fallback.get("artifacts", [])
                tools_called = fallback.get("tools_called", ["generate_contract"])

            return self._ok(
                content=contract_text,
                artifacts=artifacts,
                tools_called=tools_called,
            )
        except Exception as exc:
            logger.error(f"LegalAgent.generate_contract failed: {exc}", exc_info=True)
            return self._err(f"Contract generation failed: {exc}")

    async def extract_clauses(self, task: dict) -> dict:
        """
        Extract and categorise specific clauses from a legal document.

        Identifies: indemnity, limitation of liability, IP ownership,
        data protection, force majeure, confidentiality, dispute resolution,
        termination, governing law, entire agreement clauses.
        """
        config = task.get("_config", {})
        message = task.get("message", "")

        system_prompt = (
            "You are Leo, a specialist legal AI assistant for Mezzofy. "
            "You are extracting and categorising clauses from a legal document.\n\n"
            "For each clause identified, provide:\n"
            "1. **Clause Type** — e.g., Indemnity, Limitation of Liability, IP Ownership\n"
            "2. **Clause Text** — The exact or paraphrased text of the clause\n"
            "3. **Location** — Section number or approximate position in the document\n"
            "4. **Assessment** — Is this clause standard, favourable, or unfavourable for the user?\n"
            "5. **Risk Flag** — Any concerns with this clause?\n\n"
            "Clause categories to look for:\n"
            "- Indemnity\n- Limitation of Liability\n- IP Ownership / Assignment\n"
            "- Data Protection / Privacy\n- Force Majeure\n- Confidentiality / NDA\n"
            "- Dispute Resolution / Arbitration\n- Termination\n- Governing Law\n"
            "- Entire Agreement\n\n"
            "If no document is provided, ask the user to upload or paste the document text."
        )

        try:
            from app.llm import llm_manager as llm_mod

            extracted_text = task.get("extracted_text", "")
            task_with_prompt = dict(task)
            if extracted_text:
                task_with_prompt["message"] = (
                    f"Extract clauses from the following document:\n\n"
                    f"{extracted_text[:8000]}\n\n"
                    f"User request: {message}"
                )
            task_with_prompt["system_prompt"] = system_prompt
            result = await llm_mod.get().execute_with_tools(task_with_prompt)

            return self._ok(
                content=result.get("content", "Clause extraction complete."),
                artifacts=result.get("artifacts", []),
                tools_called=result.get("tools_called", ["extract_clauses"]),
            )
        except Exception as exc:
            logger.error(f"LegalAgent.extract_clauses failed: {exc}", exc_info=True)
            return self._err(f"Clause extraction failed: {exc}")

    async def assess_legal_risk(self, task: dict) -> dict:
        """
        Assess legal risk in a document or business scenario.

        Produces a risk register with severity ratings (High/Medium/Low),
        affected parties, recommended mitigations, and jurisdiction notes.
        """
        config = task.get("_config", {})
        message = task.get("message", "")
        jurisdiction = self._classify_jurisdiction(message)

        logger.info(f"LegalAgent.assess_legal_risk: jurisdiction={jurisdiction!r}")

        kb_context = self._load_jurisdiction_knowledge(jurisdiction)

        system_prompt = (
            "You are Leo, a specialist legal AI assistant for Mezzofy. "
            "You are performing a legal risk assessment.\n\n"
            "For each risk identified, provide:\n"
            "1. **Risk Area** — e.g., Contractual, Regulatory, IP, Employment, Tax\n"
            "2. **Severity** — High / Medium / Low\n"
            "3. **Description** — What is the risk and why does it matter?\n"
            "4. **Affected Party** — Who bears this risk?\n"
            "5. **Mitigation** — How can this risk be reduced or eliminated?\n"
            "6. **Jurisdiction Note** — Any jurisdiction-specific considerations?\n\n"
            "Present the output as a structured Risk Register table, then provide an "
            "executive summary of the top 3 highest-priority risks.\n\n"
            + (f"Jurisdiction Context:\n{kb_context}\n\n" if kb_context else "")
        )

        try:
            from app.llm import llm_manager as llm_mod

            extracted_text = task.get("extracted_text", "")
            task_with_prompt = dict(task)
            if extracted_text:
                task_with_prompt["message"] = (
                    f"Assess legal risk in the following document/scenario:\n\n"
                    f"{extracted_text[:8000]}\n\n"
                    f"User request: {message}"
                )
            task_with_prompt["system_prompt"] = system_prompt
            result = await llm_mod.get().execute_with_tools(task_with_prompt)

            return self._ok(
                content=result.get("content", "Risk assessment complete."),
                artifacts=result.get("artifacts", []),
                tools_called=result.get("tools_called", ["assess_legal_risk"]),
            )
        except Exception as exc:
            logger.error(f"LegalAgent.assess_legal_risk failed: {exc}", exc_info=True)
            return self._err(f"Legal risk assessment failed: {exc}")

    async def provide_legal_advice(self, task: dict) -> dict:
        """
        Provide jurisdiction-specific legal advisory on business matters.

        Covers: entity formation, regulatory compliance, employment law,
        data protection, IP protection, international trade, contract matters.
        Uses knowledge base files for jurisdiction-specific context.
        """
        config = task.get("_config", {})
        message = task.get("message", "")
        jurisdiction = self._classify_jurisdiction(message)

        logger.info(f"LegalAgent.provide_legal_advice: jurisdiction={jurisdiction!r}")

        kb_context = self._load_jurisdiction_knowledge(jurisdiction)

        system_prompt = (
            "You are Leo, a specialist legal AI assistant for Mezzofy. "
            "You provide legal advisory on international business law matters.\n\n"
            "Your specialisations:\n"
            "- Singapore: Companies Act, Employment Act, PDPA, MAS regulations\n"
            "- Hong Kong: Companies Ordinance, Employment Ordinance, PDPO\n"
            "- Malaysia: Companies Act 2016, Employment Act 1955, PDPA 2010\n"
            "- UAE: Commercial Companies Law, DIFC/ADGM free zone regulations\n"
            "- Saudi Arabia: Companies Law, Labor Law, Vision 2030 regulatory framework\n"
            "- Qatar: Commercial Companies Law, QFC regulations\n"
            "- Cayman Islands: Companies Act, exempted company structures, fund regulations\n\n"
            "Provide structured, practical advice. Where jurisdiction is unclear, "
            "ask the user which jurisdiction applies before proceeding.\n\n"
            + (f"Jurisdiction Knowledge:\n{kb_context}\n\n" if kb_context else "")
            + "Always be clear about limitations — recommend professional legal counsel "
            "for binding decisions."
        )

        try:
            from app.llm import llm_manager as llm_mod

            task_with_prompt = dict(task)
            task_with_prompt["system_prompt"] = system_prompt
            result = await llm_mod.get().execute_with_tools(task_with_prompt)

            return self._ok(
                content=result.get("content", "Legal advisory complete."),
                artifacts=result.get("artifacts", []),
                tools_called=result.get("tools_called", ["provide_legal_advice"]),
            )
        except Exception as exc:
            logger.error(f"LegalAgent.provide_legal_advice failed: {exc}", exc_info=True)
            return self._err(f"Legal advisory failed: {exc}")

    # ── Helper methods ─────────────────────────────────────────────────────────

    def _classify_legal_task(self, message: str) -> str:
        """
        Classify the message into one of 5 legal workflow types.

        Returns one of:
            "review_document", "generate_contract", "extract_clauses",
            "assess_legal_risk", "provide_legal_advice"
        """
        lower = message.lower()

        # Document review signals
        review_signals = [
            "review", "analyse", "analyze", "check this", "look at this",
            "what does this", "explain this contract", "explain this agreement",
            "read this", "evaluate this",
        ]
        if any(s in lower for s in review_signals) and any(
            d in lower for d in ["contract", "agreement", "nda", "document", "clause"]
        ):
            return "review_document"

        # Contract/document generation signals
        draft_signals = [
            "draft", "create", "generate", "write", "prepare", "template",
            "draw up", "make a", "need a contract", "need an agreement",
        ]
        if any(s in lower for s in draft_signals):
            return "generate_contract"

        # Clause extraction signals
        clause_signals = [
            "extract clause", "find clause", "what clause", "which clause",
            "clause library", "all clauses", "list clauses", "show clauses",
        ]
        if any(s in lower for s in clause_signals):
            return "extract_clauses"

        # Risk assessment signals
        risk_signals = [
            "legal risk", "risk assessment", "risk analysis", "risky",
            "flag issues", "red flags", "potential issues", "liability exposure",
            "what are the risks",
        ]
        if any(s in lower for s in risk_signals):
            return "assess_legal_risk"

        # Default: general legal advice / advisory
        return "provide_legal_advice"

    def _classify_jurisdiction(self, message: str) -> str:
        """
        Detect the jurisdiction from the message text.

        Returns the jurisdiction file name key (e.g., "singapore", "hong_kong")
        or "general" if no specific jurisdiction is detected.
        """
        lower = message.lower()
        for keyword, jurisdiction in _JURISDICTION_MAP.items():
            if keyword in lower:
                return jurisdiction
        return "general"

    def _get_jurisdiction_knowledge_file(self, jurisdiction: str) -> Path:
        """
        Return the path to the jurisdiction knowledge file.

        Args:
            jurisdiction: Jurisdiction file name key (e.g., "singapore").

        Returns:
            Path to the .md file (may not exist — caller must check).
        """
        return _KNOWLEDGE_BASE_PATH / "jurisdictions" / f"{jurisdiction}.md"

    def _load_jurisdiction_knowledge(self, jurisdiction: str) -> str:
        """
        Load and return jurisdiction knowledge file contents.

        Returns empty string if the file does not exist or cannot be read.
        Truncates to 3000 chars to avoid filling context.
        """
        if jurisdiction == "general":
            return ""
        kb_file = self._get_jurisdiction_knowledge_file(jurisdiction)
        try:
            if kb_file.exists():
                content = kb_file.read_text(encoding="utf-8")
                return content[:3000]  # Truncate to manage context
        except Exception as e:
            logger.warning(f"LegalAgent: could not load KB file {kb_file}: {e}")
        return ""

    def _load_contract_template(self, message: str, jurisdiction: str) -> str:
        """
        Load the most appropriate contract template from the knowledge base.

        Detects contract type from message, then loads the matching template file.
        Returns empty string if no template is found.
        """
        lower = message.lower()

        # Map contract type keywords to template file names
        type_map = [
            (["nda", "non-disclosure", "confidentiality agreement"], "nda"),
            (["service agreement", "services agreement", "sow", "statement of work"], "service_agreement"),
            (["employment contract", "employment agreement", "job offer"], "employment_contract"),
            (["mou", "memorandum of understanding"], "mou"),
            (["vendor agreement", "supplier agreement"], "vendor_agreement"),
            (["shareholders agreement", "shareholder agreement"], "shareholders_agreement"),
            (["loi", "letter of intent"], "loi"),
        ]

        contract_type = "nda"  # default
        for keywords, template_name in type_map:
            if any(kw in lower for kw in keywords):
                contract_type = template_name
                break

        # Try jurisdiction-specific template first, then general
        for jur in (jurisdiction, "general"):
            template_path = _KNOWLEDGE_BASE_PATH / "templates" / jur / f"{contract_type}.md"
            try:
                if template_path.exists():
                    content = template_path.read_text(encoding="utf-8")
                    return content[:2000]  # Truncate to manage context
            except Exception as e:
                logger.warning(f"LegalAgent: could not load template {template_path}: {e}")

        return ""
